#!/bin/bash

mv home.mine home.html
#rm -r *.mine
#rm index.html

# notebooks
mv notebooks/index.mine notebooks/index.html
rm -rf notebooks/*.mine

# book reviews
tmp="bookReviews"
rm -rf $tmp/index.* $tmp/data/index.*
rm -rf $tmp/*.mine $tmp/data/*.mine

#poetry and quotes
tmp="poetryQuotes"
rm -rf $tmp/index.* $tmp/data/index.*
rm -rf $tmp/*.mine $tmp/data/*.mine

#research
tmp="research"
rm -rf $tmp/index.* $tmp/data/index.*
rm -rf $tmp/*.mine $tmp/data/*.mine

#main
tmp="main"
rm -rf $tmp/index.* $tmp/index.*
rm -rf $tmp/*.mine $tmp/*.mine

