#!/bin/bash

mv index.mine index.html
#rm -r *.mine
#rm index.html

# notebooks
mv notebooks/index.mine notebooks/index.html
rm -r notebooks/*.mine

# book reviews
tmp="bookReviews"
rm -r $tmp/index.* $tmp/data/index.*
rm -r $tmp/*.mine $tmp/data/*.mine

#poetry and quotes
tmp="poetryQuotes"
rm -r $tmp/index.* $tmp/data/index.*
rm -r $tmp/*.mine $tmp/data/*.mine

#research
tmp="research"
rm -r $tmp/index.* $tmp/data/index.*
rm -r $tmp/*.mine $tmp/data/*.mine
